language: java
jdk:
  - openjdk17

# branches
# - Travis CI를 어느 브랜치가 푸시될 때 수행할지 지정한다.
# - 현재 옵션은 오직 master 브랜치에 push될 때만 수행한다.
branches:
  only:
    - master

# cache
# - gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여,
# - 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정한다.
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'



#before_script:
#  - chmod +x ./gradlew



# script
# - master 브랜치에 푸시되었을 때 수행하는 명령어이다.
# - 여기서는 프로젝트 내부에 둔 gradlew을 통해 clean & build를 수행한다.
script: "./gradlew clean build"

# notifications
# - Travis CI 실행 완료 시 자동으로 알람이 가도록 설정한다.
# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - melitina915@sookmyung.ac.kr